services:
  nginx:
    image: nginx:1.23.1-alpine
    network_mode: host
    environment:
      - NGINX_PORT1=${NGINX_PORT:-5600}
      - NGINX_PORT2=${NGINX_PORT:-5601}
      - NGINX_PORT2=${NGINX_PORT:-5601}
      - DEV_PORT=${DEV_PORT:-5599}
      - DEV_UI_PORT=${DEV_UI_PORT:-5599}
    volumes:
      - ./dev/resources/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro